server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ipo_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ipo-realm